### ISSUE TITLE
Incoformidade de template mobile/desktop

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/cadastro-perguntas#10]
![image](https://user-images.githubusercontent.com/34348097/171949667-8a80550d-24ba-4970-b2db-1b6e36f6ae06.png)  Fiz a alteração da imagem do cabeçalho para ficar igual ao FIGMA, mas em tela de dektop estamos com layout de mobile.  
Todo o padrão de desktop deve seguir o layout a seguir do FIGMA:  
![image](https://user-images.githubusercontent.com/34348097/171949782-9668f4a8-91ea-4a57-8b86-6627f5275d0b.png)

**Comment by Jefferson472** [comment]
Este ponto não ficou claro, qual tela não está como o Figma?

**Comment by filiperochalopes** [comment]
A questão era que a tela de login, no mobile não estava com a largura que estava desenhada no template desktop, mas isso não fará tanta diferença no final. Se eu quiser eu mudo depois, fechando a issue
