### ISSUE TITLE
Inconformidade de margens

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/cadastro-perguntas#11]
![image](https://user-images.githubusercontent.com/34348097/171950009-339bfa44-ded5-4aad-918e-bbaff544a312.png)  
Revisar margens do layout, bem como tamanhos da fonte.

**Comment by Jefferson472** [comment]
Feito a revisão das margens. 
Família e tamanho das fontes já estão de acordo com o projeto do Figma.
