### ISSUE TITLE
Posicionamento do rodapé

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/cadastro-perguntas#12]
![image](https://user-images.githubusercontent.com/34348097/171950215-29177462-6515-4c19-9d1f-83902b30b588.png)  
O rodapé deve ficar sempre no fim da página (zona vermelha) independente do tamanho do conteúdo. https://stackoverflow.com/questions/643879/css-to-make-html-page-footer-stay-at-bottom-of-the-page-with-a-minimum-height-b

**Comment by Jefferson472** [comment]
Feito a correção do rodapé
https://github.com/Jogo-da-Biblia/cadastro-perguntas/pull/7/commits/8574536a962e0e3d0426af86830243950ea9ce18
