### ISSUE TITLE
Conformidade de cabeçallho e logo

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/cadastro-perguntas#14]
Consegui corrigir a logo, que aparentemente estava havendo dificuldade de colocar os efeitos css corretos.  
![image](https://user-images.githubusercontent.com/34348097/171951452-7ddd37dd-ba99-49f8-b7f1-7a7b1436015c.png)  
Agora preciso que as outras telas sejam revisadas e que as imagens que não estão sendo utilizadas sejam excluídas do projeto.

**Comment by Jefferson472** [comment]
Feito a correção dos cabeçalhos.
https://github.com/Jogo-da-Biblia/cadastro-perguntas/pull/7/commits/c56eda978ae89f1ed419f0f5b616bd2e3275f11e

**Comment by Jefferson472** [comment]
Ficou faltando um margin para ajustar a distância corretamente do título ao logo:
https://github.com/Jogo-da-Biblia/cadastro-perguntas/pull/7/commits/d8a0c00f3b0c8c6d933e30704d94dd77055e2de5

**Comment by filiperochalopes** [comment]
Notei que ainda não foram excluídos do projeto as imagens que não estão sendo utilizadas:  
![image](https://user-images.githubusercontent.com/34348097/172683746-05b8892a-d827-4cce-ae87-6fa597e360a0.png)  
Favor realizar essa limpeza

**Comment by Jefferson472** [comment]
Feito a limpeza
https://github.com/Jogo-da-Biblia/cadastro-perguntas/commit/69e827763e7494f23a8f0e15b7ce559f62e90edb
