### ISSUE TITLE
Referência de Livro-Capitulo

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/cadastro-perguntas#16]
Como `Livro-Capitulo` é uma pergunta que precisa estar de acordo com as Escrituras apenas, não pode ter uma referência de fora, portanto, essa opção deve ser retirada aqui:  
![image](https://user-images.githubusercontent.com/34348097/172646041-5a3fa020-7a26-4ed0-843f-baf55351f782.png)  
![image](https://user-images.githubusercontent.com/34348097/172647251-b8909c4b-a7f7-4bd9-98a4-a50f05baebcf.png)

**Comment by Jefferson472** [comment]
Feito a correção
https://github.com/Jogo-da-Biblia/cadastro-perguntas/commit/22c2d5fef7e4720c3e551f771c283b75e9a0676d

![image](https://user-images.githubusercontent.com/43066724/172743127-d9de8c46-1dde-4780-8ff4-bf5f3740f1b3.png)

Obs.: Para ser possível salvar a referência o versículo é necessária, então Referência Livro Capítulo será refenciado em outras referências 

![image](https://user-images.githubusercontent.com/43066724/172743275-8d988f54-fa97-4167-9ee7-9e49414ca12e.png)

**Comment by filiperochalopes** [comment]
Não. Ele deve ser exatamente igual ao de Referência Completa. Só que o versículo sempre será 1 (um) e não será cobrado na resposta

**Comment by Jefferson472** [comment]
Feito a correção para sempre salvar como versículo 1 

https://github.com/Jogo-da-Biblia/cadastro-perguntas/commit/31726cb9e725d6904efb40cc65bb73e2c3822afc
