### ISSUE TITLE
Alternativas de Resposta Simples

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/cadastro-perguntas#17]
![image](https://user-images.githubusercontent.com/34348097/172646294-783a4df0-26ab-491c-bd36-90c534d8c8e1.png)  
Conforme em FIGMA, não sei se ficou claro, deixei em um comentário lá. `Resposta Simples` deve ser exatamente igual à Multipla Escolha, com exceção de que pode ser cadastrada mais de uma resposta correta.  
![image](https://user-images.githubusercontent.com/34348097/172647086-af4526e6-fd02-4549-97a1-3e58ff7a1d0a.png)

**Comment by Jefferson472** [comment]
Feito a correção. Agora resposta de múltipla escolha só pode ter uma alternativa correta e resposta simples pode ter N alternativas corretas.

https://github.com/Jogo-da-Biblia/cadastro-perguntas/commit/0406523afe44253f8cbab32195f43788c3b1c482
