### ISSUE TITLE
Alternativas em Múltipla Escolha

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/cadastro-perguntas#18]
- [x] Alternativas não estão dispostas na ordem como FIGMA, A alternativa a ser inserida fica antes do botão de "Adicionar alternativa"
- [x] O placeholder "descreva a alternativa e clique em adicionar, assinale a alternativa que deve ficar como correta" não aparece no textarea da alternativa a ser inserida
- [x] Label de "Alternativa correta" não está aparecendo
- [x] Clique no "lixinho" está abrangendo grande área e não só a área do ícone
- [x] Está sendo possível adicionar mais de uma alternativa correta em "Multipla Escolha"
- [ ] Campo select não está estilizado ![image](https://user-images.githubusercontent.com/34348097/172648806-baa7328a-19b7-4009-a5c6-6c6137b543f2.png) >> ![image](https://user-images.githubusercontent.com/34348097/172648862-c81f3198-b2bc-4253-a2ed-0e8cda28fa13.png)

Está seguindo um padrão bem diferente do FIGMA e a label de "Alternativa correta não aparece".  
Desenvolvido:  
![image](https://user-images.githubusercontent.com/34348097/172647756-d55a375f-2094-47f3-a415-d6ac8ca75ebb.png)  
FIgma:  
![image](https://user-images.githubusercontent.com/34348097/172647989-a0db272f-2682-420a-9865-99cd33cdb37e.png)

**Comment by Jefferson472** [comment]
Feito as correções.

https://github.com/Jogo-da-Biblia/cadastro-perguntas/commit/b1d1c486e66024fecd7c6f0467c060ab33d5da47

Consegui estilizar o input tipo radio, mas infelizmente não consegui estilizar o checkbox das alternativas
![image](https://user-images.githubusercontent.com/43066724/173240637-8f74feaa-e36c-47bc-a1d5-d695de9bc9d6.png)

![image](https://user-images.githubusercontent.com/43066724/173240665-94933902-3def-4c71-a5f3-d1f77fb633d5.png)

**Comment by Jefferson472** [comment]
A estilização do checkbox foi criada conforme abaixo,

![image](https://user-images.githubusercontent.com/43066724/173341915-8cd4f9db-3117-4c6f-af3c-62efedd90702.png)

Para chama-la basta adicionar a classe "square" junto com a classe "checkmark" dentro de uma label com a class "custom__radio". Segue um  exemplo:


```
<label for="radio-escolha" class="card__multipla custom__radio custom__radio">
      <input type="radio" name="tipo_resposta" value="MES" id="radio-escolha" checked="checked">Múltipla Escolha
      <span class="checkmark square"></span>
 </label>
```

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/174049396-a08c7eb6-4287-4582-8454-bf8e1b4b6a92.png)
Não identifiquei essa alteração no sistema, porém não fará diferença no final.
