### ISSUE TITLE
Acessando como revisor eu tenho acesso a publicar

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/cadastro-perguntas#20]
![image](https://user-images.githubusercontent.com/34348097/172656623-d3b417a9-1798-4901-994b-0567f0507185.png)  
Não deve ser assim, ao criar uma pergunta eu não devo poder revisar nem publicar

**Comment by Jefferson472** [comment]
Não consegui replicar o erro mencionado. Veja que na tela abaixo eu criei a pergunta como revisor, e como revisor possa revisa-la, mas a opção de publicar não é vista.

![image](https://user-images.githubusercontent.com/43066724/173187675-63627f17-8f8e-4720-aaf8-ef5a8f48e3c0.png)

**Comment by Jefferson472** [comment]
Na correção abaixo, implementei uma função para remover os campos de revisão e publicado sempre que as condições de grupo não forem atendidas. Acredito que isso irá consertar o bug que você recebeu. Me avise se acontecer o erro novamente para tentarmos outra solução.

https://github.com/Jogo-da-Biblia/cadastro-perguntas/commit/260101c60948ab392623edba2646fd33be30c78f

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/174054103-219ec998-e180-498c-9e9a-884da2062aa5.png)
Ao clicar em revisar e abrir novamente não fica marcado como revisado.  
![image](https://user-images.githubusercontent.com/34348097/174054880-6b9802c8-d175-4b57-ab0c-1eece90e8596.png)
A ideia é que não precise do checkbox, mas sim que, ao clicar em "Revisar" o item seja marcado como revisado. Se o item estiver marcado como Publicado o Revisor tem o botão "Revisar" desabilitado.

**Comment by Jefferson472** [comment]
Feito a correção 

https://github.com/Jogo-da-Biblia/cadastro-perguntas/commit/4ebca102a55f2109fb37f9edb7a858dc7ec318e4
