### ISSUE TITLE
Publicar sem revisar

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/cadastro-perguntas#21]
![image](https://user-images.githubusercontent.com/34348097/172673405-64602b70-1ad7-4e0b-9f57-67287ecc69ec.png)  
Está sendo possível publicar sem nem mesmo revisar

**Comment by Jefferson472** [comment]
Feito a correção. Antes, mesmo aparecendo a opção de Publicar, somente objetos revisados podiam ser publicados (ao clicar não era feito a publicação). Agora, a opção Publicado só aparece quando o objeto for status revisado

https://github.com/Jogo-da-Biblia/cadastro-perguntas/commit/260101c60948ab392623edba2646fd33be30c78f

**Comment by Jefferson472** [comment]
Feito a correção 

https://github.com/Jogo-da-Biblia/cadastro-perguntas/commit/4ebca102a55f2109fb37f9edb7a858dc7ec318e4
