### ISSUE TITLE
Media queries com breakpoints não específicos

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/cadastro-perguntas#22]
Existem alguns tamanhos de telas não funcionais. Esse, por exemplo é um iPad  
![image](https://user-images.githubusercontent.com/34348097/172680696-ba45c098-8932-4213-9638-1c89e86137e8.png)  
![image](https://user-images.githubusercontent.com/34348097/172680553-f91319a6-c937-4967-ac00-ecfa33251bd8.png)

**Comment by Jefferson472** [comment]
Feito a correção. Agora todo conteúdo fica centrilizado no centro da tela e se ajustam ao tamanhos de tela.

https://github.com/Jogo-da-Biblia/cadastro-perguntas/commit/470743f448951996a911aeb6155659ac875052c4

![image](https://user-images.githubusercontent.com/43066724/173194478-1f671c48-c246-4252-958e-5efda9c60d1a.png)
