### ISSUE TITLE
Logo não centralizada em dispositivos móveis

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/cadastro-perguntas#23]
![image](https://user-images.githubusercontent.com/34348097/172681131-bb893e62-1ccc-476f-8c78-1eb089222312.png)

**Comment by Jefferson472** [comment]
Feito a correção.

https://github.com/Jogo-da-Biblia/cadastro-perguntas/commit/e6ead8c1dbed16a6310491dd45b786e0cf496174

![image](https://user-images.githubusercontent.com/43066724/173191870-9c6a0f5e-d18a-439e-8011-1eab5bb7c325.png)
