### ISSUE TITLE
Página de login não centralizada em mobile

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/cadastro-perguntas#24]
![image](https://user-images.githubusercontent.com/34348097/172687113-34076c3d-3a84-48c7-9900-7f0ca7e2e8c9.png)

**Comment by Jefferson472** [comment]
Feito a correção. 

https://github.com/Jogo-da-Biblia/cadastro-perguntas/commit/470743f448951996a911aeb6155659ac875052c4

![image](https://user-images.githubusercontent.com/43066724/173194454-7a2c8068-b21b-4c2e-8996-f1d772f96617.png)
