### ISSUE TITLE
Erro após publicar pergunta não revisada pelo botão de Publicar

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/cadastro-perguntas#25]
Após entrar como Publicador em um post ainda não revisado tinha um botão no rodapé escrito "Publicar", cliquei nele. Depois disso ao tentar editar qualquer pergunta retorna esse erro:  
![image](https://user-images.githubusercontent.com/34348097/173957014-3701db2e-4d3a-4dcf-91c8-85caed27061a.png)

**Comment by filiperochalopes** [comment]
E o status não muda para publicado  
![image](https://user-images.githubusercontent.com/34348097/173957257-7291cb01-6df2-4a94-8ab1-c1c9a411cc89.png)

**Comment by filiperochalopes** [comment]
x

**Comment by filiperochalopes** [comment]
Após reiniciado o computador, voltou a funcionar

**Comment by filiperochalopes** [comment]
O erro ocorre apenas como "revisor"

**Comment by Jefferson472** [comment]
Feito a alteração do sistema Revisor/Publicador. Agora os campos não serão mais excluídos e serão exibidos como leitura para cada caso.

https://github.com/Jogo-da-Biblia/cadastro-perguntas/commit/fa577490609208157e9686e3bbfbe2feb281692a
