### ISSUE TITLE
"Publicado em" carrega data sem ter sido publicado

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/cadastro-perguntas#26]
![image](https://user-images.githubusercontent.com/34348097/174058390-58bbbb64-b337-4faf-b0c9-040cc76c6c81.png)  
Imagino que algo possa ter a ver com o `auto_now_add`  
![image](https://user-images.githubusercontent.com/34348097/174058449-0bb88a7e-7da3-48cd-8b86-2c2194827a71.png)
![image](https://user-images.githubusercontent.com/34348097/174058592-dca3fdce-b58f-4f88-8f0f-ea41ee641638.png)

**Comment by Jefferson472** [comment]
Sim, realmente era isso, foi feito a remoção do auto_now, pois não era necessária, já que o preenchimento das datas estão sendo tratadas no momento da verificação da revisão ou publicação.

https://github.com/Jogo-da-Biblia/cadastro-perguntas/commit/1b361b7af159e9eca427ea6c7570ed6da10f41a6
