### ISSUE TITLE
Método de Autenticação Postgres Image

### ISSUE THREAD

**Issue by Jefferson472** [Jogo-da-Biblia/cadastro-perguntas#8]
Esta é uma feature insegura do postgres, deve ser usado somendo no ambiente de desenvolvimento. No ambiente de produção deve usar modelo de autenticação md5 ou shacram 256 (atualmente, pycopg não está atualizada para o shacram256)

https://github.com/Jogo-da-Biblia/cadastro-perguntas/blob/4a3ea93771a30a48f991030c5f7ebceb01bb320a/docker-compose.yml#L35

**Comment by filiperochalopes** [comment]
Já removi e estou usando o método de produção.
