### ISSUE TITLE
Login com usuário

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/cadastro-perguntas#9]
![image](https://user-images.githubusercontent.com/34348097/171947822-a00c4953-f536-488a-a423-b75cc8122f90.png)  
Ao tentar fazer login com usuário dá erro. Deve ser possível usar tanto o email quanto o usuário, como o próprio `label` sugere.

**Comment by Jefferson472** [comment]
Feito a correção para suportart login via usuário ou email

**Comment by filiperochalopes** [comment]
Muito bom  
![image](https://user-images.githubusercontent.com/34348097/172684823-405d9739-2184-4d27-811f-3ef54d297efb.png)
